apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: choosepath-legacy-develop
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
        app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: db-image
          imagePullPolicy: IfNotPresent
          env:
              - name: MYSQL_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: common-configmap
                    key: mysql-db
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
            # LivenessProbe using mysqladmin ping

          livenessProbe:
              tcpSocket:
                port: 3306
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 20
              timeoutSeconds: 3
            # ReadinessProbe using mysqladmin ping
          readinessProbe:
              tcpSocket:
                port: 3306
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 5
              timeoutSeconds: 3
          resources:
              limits:
                cpu: 1
                memory: 2Gi
              requests:
                cpu: 500m
                memory: 1Gi
      volumes:
          - name: mysql-data
            persistentVolumeClaim:
              claimName: mysql-pvc