apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: db-image
    newName: mysql
    newTag: "8.0"

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - spc.yaml
