apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: choosepath-legacy-develop
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3303
      targetPort: 3303
  selector:
    app: db
