apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
    deployment: webapp
  name: webapp
  namespace: choosepath-legacy-develop
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: webapp
      deployment: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: webapp
        deployment: webapp
    spec:
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: timezone
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: mysql-db-host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: mysql-db
            - name: DB_LOGS_LEVEL
              value: DEBUG

          image: webapp-image
          imagePullPolicy: Always
          name: auth-service
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
