apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: choosepath-legacy-develop
  labels:
    app: webapp-service
spec:
  type: ClusterIP
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: webapp-service